#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Opgave_2._1.Database
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="shocknet_dk_db_shock")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertkunde(kunde instance);
    partial void Updatekunde(kunde instance);
    partial void Deletekunde(kunde instance);
    partial void InsertVare(Vare instance);
    partial void UpdateVare(Vare instance);
    partial void DeleteVare(Vare instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::Opgave_2._1.Properties.Settings.Default.shocknet_dk_db_shockConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<kunde> kundes
		{
			get
			{
				return this.GetTable<kunde>();
			}
		}
		
		public System.Data.Linq.Table<Vare> Vares
		{
			get
			{
				return this.GetTable<Vare>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.kunde")]
	public partial class kunde : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _kundeNr;
		
		private string _Fornavn;
		
		private string _Efternavn;
		
		private int _TelefonNr;
		
		private string _Email;
		
		private string _Adresse;
		
		private int _cprnummer;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnkundeNrChanging(int value);
    partial void OnkundeNrChanged();
    partial void OnFornavnChanging(string value);
    partial void OnFornavnChanged();
    partial void OnEfternavnChanging(string value);
    partial void OnEfternavnChanged();
    partial void OnTelefonNrChanging(int value);
    partial void OnTelefonNrChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnAdresseChanging(string value);
    partial void OnAdresseChanged();
    partial void OncprnummerChanging(int value);
    partial void OncprnummerChanged();
    #endregion
		
		public kunde()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kundeNr", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int kundeNr
		{
			get
			{
				return this._kundeNr;
			}
			set
			{
				if ((this._kundeNr != value))
				{
					this.OnkundeNrChanging(value);
					this.SendPropertyChanging();
					this._kundeNr = value;
					this.SendPropertyChanged("kundeNr");
					this.OnkundeNrChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fornavn", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Fornavn
		{
			get
			{
				return this._Fornavn;
			}
			set
			{
				if ((this._Fornavn != value))
				{
					this.OnFornavnChanging(value);
					this.SendPropertyChanging();
					this._Fornavn = value;
					this.SendPropertyChanged("Fornavn");
					this.OnFornavnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Efternavn", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Efternavn
		{
			get
			{
				return this._Efternavn;
			}
			set
			{
				if ((this._Efternavn != value))
				{
					this.OnEfternavnChanging(value);
					this.SendPropertyChanging();
					this._Efternavn = value;
					this.SendPropertyChanged("Efternavn");
					this.OnEfternavnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TelefonNr", DbType="Int NOT NULL")]
		public int TelefonNr
		{
			get
			{
				return this._TelefonNr;
			}
			set
			{
				if ((this._TelefonNr != value))
				{
					this.OnTelefonNrChanging(value);
					this.SendPropertyChanging();
					this._TelefonNr = value;
					this.SendPropertyChanged("TelefonNr");
					this.OnTelefonNrChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Adresse", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Adresse
		{
			get
			{
				return this._Adresse;
			}
			set
			{
				if ((this._Adresse != value))
				{
					this.OnAdresseChanging(value);
					this.SendPropertyChanging();
					this._Adresse = value;
					this.SendPropertyChanged("Adresse");
					this.OnAdresseChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cprnummer", DbType="Int NOT NULL")]
		public int cprnummer
		{
			get
			{
				return this._cprnummer;
			}
			set
			{
				if ((this._cprnummer != value))
				{
					this.OncprnummerChanging(value);
					this.SendPropertyChanging();
					this._cprnummer = value;
					this.SendPropertyChanged("cprnummer");
					this.OncprnummerChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Vare")]
	public partial class Vare : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Varenr;
		
		private double _Pris;
		
		private double _Storrelse;
		
		private string _VareNavn;
		
		private System.Nullable<System.DateTime> _Dato;
		
		private System.Nullable<int> _kundeNr;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnVarenrChanging(int value);
    partial void OnVarenrChanged();
    partial void OnPrisChanging(double value);
    partial void OnPrisChanged();
    partial void OnStorrelseChanging(double value);
    partial void OnStorrelseChanged();
    partial void OnVareNavnChanging(string value);
    partial void OnVareNavnChanged();
    partial void OnDatoChanging(System.Nullable<System.DateTime> value);
    partial void OnDatoChanged();
    partial void OnkundeNrChanging(System.Nullable<int> value);
    partial void OnkundeNrChanged();
    #endregion
		
		public Vare()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Varenr", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Varenr
		{
			get
			{
				return this._Varenr;
			}
			set
			{
				if ((this._Varenr != value))
				{
					this.OnVarenrChanging(value);
					this.SendPropertyChanging();
					this._Varenr = value;
					this.SendPropertyChanged("Varenr");
					this.OnVarenrChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pris", DbType="Float NOT NULL")]
		public double Pris
		{
			get
			{
				return this._Pris;
			}
			set
			{
				if ((this._Pris != value))
				{
					this.OnPrisChanging(value);
					this.SendPropertyChanging();
					this._Pris = value;
					this.SendPropertyChanged("Pris");
					this.OnPrisChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Storrelse", DbType="Float NOT NULL")]
		public double Storrelse
		{
			get
			{
				return this._Storrelse;
			}
			set
			{
				if ((this._Storrelse != value))
				{
					this.OnStorrelseChanging(value);
					this.SendPropertyChanging();
					this._Storrelse = value;
					this.SendPropertyChanged("Storrelse");
					this.OnStorrelseChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VareNavn", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string VareNavn
		{
			get
			{
				return this._VareNavn;
			}
			set
			{
				if ((this._VareNavn != value))
				{
					this.OnVareNavnChanging(value);
					this.SendPropertyChanging();
					this._VareNavn = value;
					this.SendPropertyChanged("VareNavn");
					this.OnVareNavnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dato", DbType="DateTime")]
		public System.Nullable<System.DateTime> Dato
		{
			get
			{
				return this._Dato;
			}
			set
			{
				if ((this._Dato != value))
				{
					this.OnDatoChanging(value);
					this.SendPropertyChanging();
					this._Dato = value;
					this.SendPropertyChanged("Dato");
					this.OnDatoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kundeNr", DbType="Int")]
		public System.Nullable<int> kundeNr
		{
			get
			{
				return this._kundeNr;
			}
			set
			{
				if ((this._kundeNr != value))
				{
					this.OnkundeNrChanging(value);
					this.SendPropertyChanging();
					this._kundeNr = value;
					this.SendPropertyChanged("kundeNr");
					this.OnkundeNrChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
